channels = ["trance", 
            "00sclubhits", 
            "ambient", 
            "bassnjackinhouse", 
            "bassline", 
            "bigbeat", 
            "bigroomhouse", 
            "breaks", 
            "chillhop", 
            "chillout", 
            "chilloutdreams", 
            "chillstep", 
            "chiptunes", 
            "classiceurodance", 
            "classiceurodisco", 
            "classictrance",
            "classicvocaltrance", 
            "clubdubstep", 
            "club", 
            "cosmicdowntempo", 
            "djmixes", 
            "darkdnb", 
            "deephouse", 
            "deepnudisco", 
            "deeptech",
            "discohouse", 
            "downtempolounge", 
            "drumandbass", 
            "dubstep", 
            "ebm", 
            "eclectronica", 
            "electro", 
            "electroswing", 
            "electronicpioneers",
            "electropop", 
            "epictrance", 
            "eurodance", 
            "funkyhouse", 
            "futuregarage", 
            "futuresynthpop", 
            "gabber", 
            "glitchhop", 
            "goapsy", 
            "handsup",
            "harddance", 
            "hardtechno", 
            "hardcore", 
            "hardstyle", 
            "house", 
            "jungle", 
            "latinhouse", 
            "liquiddnb", 
            "liquiddubstep", 
            "lounge", 
            "mainstage",
            "minimal", 
            "moombahton", 
            "nightcore", 
            "nudisco", 
            "oldschoolacid", 
            "oldschoolhouse", 
            "oldschoolrave", 
            "classictechno", 
            "progressive", 
            "progressivepsy", 
            "psychill", 
            "psybient", 
            "russianclubhits", 
            "sankeys", 
            "scousehouse", 
            "spacemusic", 
            "techhouse", 
            "techno", 
            "trap",
            "tribalhouse", 
            "ukgarage", 
            "umfradio", 
            "undergroundtechno", 
            "vocalchillout", 
            "vocallounge", 
            "vocaltrance"]

var shuffleButtonLI = document.createElement("li");
var shuffleButtonA = document.createElement("a");
shuffleButtonA.innerHTML = "Shuffle Channel";
shuffleButtonLI.onclick = function () { 
       randomChan = channels[Math.floor(Math.random()*channels.length)];
       window.location.replace(randomChan);
      };
shuffleButtonLI.appendChild(shuffleButtonA);
var nav = document.querySelector('nav[class="main"]')
nav.childNodes[1].appendChild(shuffleButtonLI);

